import { DrinkData } from "../schema/orderTypes";

const DRINK_WITH_MILK: DrinkData[] = [
  {
    name: [
      "Pearl Latte with Brown Sugar",
      "Assam Black Tea",
      "Black Tea Latte",
      "Chocolate Latte",
      "Pearl Matcha Latte",
      "Pearl Taro Latte",
      "Power Taro Pudding Pearl Milk",
      "Taro Sago",
    ],
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: ["Soy milk", "Almond milk", "Lactose free milk", "Regular milk"],
  },
];

const DRINK_WITHOUT_MILK: DrinkData[] = [
  {
    name: [
      "CMF Green Tea",
      "CMF Black Tea",
      "CMF Oolong Tea",
      "CMF Rose",
      "CMF Mango",
      "CMF Chocolate",
      "CMF Matcha",
      "Jin Xuan Oolong Tea",
      "Assam Black Tea",
      "Jasmine Green Tea",
      "Winter Melon Drink",
      "Rose Oolong Tea",
      "Grape Fruit Green Tea with Agar BB",
      "Winter Melon with Lemon",
      "Honey Lemon with Aloe Vera",
      "Passion Fruit with Basil Seeds",
      "Passion Fruit QQ",
      "Yakult Green Tea with Aloe Vera",
      "Pearl Milk Green Tea with Taro",
      "Coffee Milk Tea",
      "Matcha Milk Tea with Redbean",
      "Signature Lite Fruit Tea",
      "Mango Fruit Tea",
      "Passion Fruit Green Tea",
      "Cranberry Green Tea",
      "Plum Green Tea",
      "Special Plum Juice",
      "Lychee Ice Tea",
      "38 Milk King",
      "Original Milk Tea",
      "Green Milk Tea",
      "Oolong Milk Tea",
      "Chocolate Milk Tea",
      "Kungfu Ginger Milk Tea",
      "Rose Milk Tea",
    ],
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
];

export const ORDER_LIST = DRINK_WITH_MILK.concat(DRINK_WITHOUT_MILK);
