import { DrinkData } from "../schema/orderTypes";

const CMF: DrinkData[] = [
  {
    name: "CMF Green Tea",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "CMF Black Tea",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "CMF Oolong Tea",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "CMF Rose",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "CMF Mango",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "CMF Chocolate",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "CMF Matcha",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
];

const ORIGINAL: DrinkData[] = [
  {
    name: "Jin Xuan Oolong Tea",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "Assam Black Tea",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "Jasmine Green Tea",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "Winter Melon Drink",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
];

const LATTE: DrinkData[] = [
  {
    name: "Pearl Latte with Brown Sugar",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: ["Soy milk", "Almond milk", "Lactose free milk", "Regular milk"],
  },
  {
    name: "Assam Black Tea",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: ["Soy milk", "Almond milk", "Lactose free milk", "Regular milk"],
  },
  {
    name: "Black Tea Latte",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: ["Soy milk", "Almond milk", "Lactose free milk", "Regular milk"],
  },
  {
    name: "Chocolate Latte",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: ["Soy milk", "Almond milk", "Lactose free milk", "Regular milk"],
  },
  {
    name: "Pearl Matcha Latte",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: ["Soy milk", "Almond milk", "Lactose free milk", "Regular milk"],
  },
  {
    name: "Pearl Taro Latte",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: ["Soy milk", "Almond milk", "Lactose free milk", "Regular milk"],
  },
];

const UNCATEGORIZED: DrinkData[] = [
  {
    name: "Power Taro Pudding Pearl Milk",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: ["Soy milk", "Almond milk", "Lactose free milk", "Regular milk"],
  },
  {
    name: "Taro Sago",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: ["Soy milk", "Almond milk", "Lactose free milk", "Regular milk"],
  },
  {
    name: "Rose Oolong Tea",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "Grape Fruit Green Tea with Agar BB",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "Winter Melon with Lemon",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "Honey Lemon with Aloe Vera",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "Passion Fruit with Basil Seeds",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "Passion Fruit QQ",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "Yakult Green Tea with Aloe Vera",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "Pearl Milk Green Tea with Taro",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "Coffe Milk Tea",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "Matcha Milk Tea with Redbean",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
];

const FRUIT: DrinkData[] = [
  {
    name: "Signature Lite Fruit Tea",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "Mango Fruit Tea",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "Passion Fruit Green Tea",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
];

const FRUIT1: DrinkData[] = [
  {
    name: "Cranberry Green Tea",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "Plum Green Tea",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "Special Plum Juice",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "Lychee Ice Tea",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
];

const MILK_TEA: DrinkData[] = [
  {
    name: "38 Milk King",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "Original Milk Tea",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "Green Milk Tea",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "Oolong Milk Tea",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "Chocolate Milk Tea",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "Kungfu Ginger Milk Tea",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
  {
    name: "Rose Milk Tea",
    size: ["Large", "Regular"],
    sweetness: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    ice: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    topping: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: null,
  },
];

export const KF_TEA_LIST = CMF.concat(
  ORIGINAL,
  LATTE,
  UNCATEGORIZED,
  FRUIT,
  FRUIT1,
  MILK_TEA
);
